/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.iceberg.actions;

import org.apache.iceberg.ContentFile;
import org.apache.iceberg.ContentScanTask;
import org.apache.iceberg.io.CloseableIterable;

/**
 * Result of the file rewrite planning as generated by the {@link FileRewritePlanner#plan()}.
 *
 * <p>The plan contains the stream of the planned groups and statistics about the number of the
 * generated groups, like the total number of the groups and the groups per partition. The plan also
 * contains some calculated values required by the {@link FileRewriteExecutor}s where the values are
 * based on the input data and the planning parameters.
 *
 * <p>Groups in a plan could be processed independently. For example, in Spark this means that each
 * group would be rewritten in its own Spark job.
 *
 * @param <PI> the Java type of the plan info
 * @param <FGI> the Java type of the file group info
 * @param <T> the Java type of the tasks to read content files
 * @param <F> the Java type of the content files
 * @param <G> the Java type of the planned groups
 */
public abstract class FileRewritePlan<
    PI extends FileRewritePlanInfo,
    FGI,
    T extends ContentScanTask<F>,
    F extends ContentFile<F>,
    G extends FileRewriteGroup<FGI, T, F>> {
  private final CloseableIterable<G> groups;
  private final PI planInfo;

  public FileRewritePlan(CloseableIterable<G> groups, PI planInfo) {
    this.groups = groups;
    this.planInfo = planInfo;
  }

  /** The stream of the generated {@link FileRewriteGroup}s. */
  public CloseableIterable<G> groups() {
    return groups;
  }

  public PI planInfo() {
    return planInfo;
  }
}
