/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.iceberg.actions;

import java.util.Map;
import org.apache.iceberg.StructLike;

public class FileRewritePlanInfo {
  private final int totalGroupCount;
  private final Map<StructLike, Integer> groupsInPartition;
  private final long writeMaxFileSize;

  public FileRewritePlanInfo(
      int totalGroupCount, Map<StructLike, Integer> groupsInPartition, long writeMaxFileSize) {
    this.totalGroupCount = totalGroupCount;
    this.groupsInPartition = groupsInPartition;
    this.writeMaxFileSize = writeMaxFileSize;
  }

  /** The number of the generated groups in the given partition. */
  public int groupsInPartition(StructLike partition) {
    return groupsInPartition.get(partition);
  }

  /** The total number of the groups generated by this plan. */
  public int totalGroupCount() {
    return totalGroupCount;
  }

  /** Calculated maximum file size based on the planner target file size configuration */
  public long writeMaxFileSize() {
    return writeMaxFileSize;
  }
}
